mongodb:
    image: mongo:latest
    volumes: 
        - "/data/mongo/bili/db:/data/db"
        - "/data/mongo/bili/configdb:/data/configdb"
    expose: 
        - "27017"
    ports:
        - "27017:27017"

buildexe: 
    build: ./source 
    volumes:
        - "/tmp/transfer:/transfer"
    
web:
    build: ./web 
    volumes_from: 
        - buildexe 
    expose: 
        - "8000"
    ports: 
        - "80:8000" 
    links:
        - mongodb