mongodb:
    image: mongo:latest
    volumes: 
        - "/data/mongo/bili/db:/data/db"
        - "/data/mongo/bili/configdb:/data/configdb"
    expose: 
        - "27017"
    ports:
        - "27017:27017"

buildexe: 
    build: ./source 
    volumes:
        - "/tmp/transfer:/transfer"
    
web1:
    build: ./web 
    volumes_from: 
        - buildexe 
    expose: 
        - "8000"
    links:
        - mongodb

web2:
    build: ./web 
    volumes_from: 
        - buildexe 
    expose: 
        - "8000"
    links:
        - mongodb

loadbalancer:
    build: ./LB
    expose:
        - "80"
    ports:
        - "80:80"
    links:
        - web1
        - web2