mongodb:
    image: mongo:latest
    volumes: 
        - "/var/lib/docker/data/mongo:/data/db"
    expose: 
        - "27017"
    ports:
        - "27017:27017"

buildexe: 
    build: ./source 
    volumes:
        - "/transfer:/transfer"
    
web:
    build: ./web 
    volumes_from: 
        - buildexe 
    expose: 
        - "8000"
    ports: 
        - "80:8000" 
    links:
        - mongodb